name: Build and Release

on:
  push:
    tags: '*.*.*'


jobs:
  qemu_4_2:
    name: Plugin build for QEMU 4.2
    runs-on: ubuntu-latest
    steps:
    - name: Cloning plugin repo
      uses: actions/checkout@v2
    - name: Cloning qemu repo
      uses: actions/checkout@v2
      with:
          repository: qemu/qemu
          ref: v4.2.1
          path: ./qemu
    - name: Building plugin
      run: |
        make
        zip system_cover-qemu_4_2.zip libsystem_cover.so
    - name: Uploading plugin
      uses: actions/upload-artifact@v2
      with:
        name: Plugin for QEMU 4.2
        path: '*.zip'

  qemu_5_0:
    name: Plugin build for QEMU 5.0
    runs-on: ubuntu-latest
    steps:
    - name: Cloning plugin repo
      uses: actions/checkout@v2
    - name: Cloning qemu repo
      uses: actions/checkout@v2
      with:
          repository: qemu/qemu
          ref: v5.0.1
          path: ./qemu
    - name: Building plugin
      run: |
        make
        zip system_cover-qemu_5_0.zip libsystem_cover.so
    - name: Uploading plugin
      uses: actions/upload-artifact@v2
      with:
        name: Plugin for QEMU 5.0
        path: '*.zip'

  qemu_5_1:
    name: Plugin build for QEMU 5.1
    runs-on: ubuntu-latest
    steps:
    - name: Cloning plugin repo
      uses: actions/checkout@v2
    - name: Cloning qemu repo
      uses: actions/checkout@v2
      with:
          repository: qemu/qemu
          ref: v5.1.0
          path: ./qemu
    - name: Building plugin
      run: |
        make
        zip system_cover-qemu_5_1.zip libsystem_cover.so
    - name: Uploading plugin
      uses: actions/upload-artifact@v2
      with:
        name: Plugin for QEMU 5.1
        path: '*.zip'

  qemu_5_2:
    name: Plugin build for QEMU 5.2
    runs-on: ubuntu-latest
    steps:
    - name: Cloning plugin repo
      uses: actions/checkout@v2
    - name: Cloning qemu repo
      uses: actions/checkout@v2
      with:
          repository: qemu/qemu
          ref: v5.2.0
          path: ./qemu
    - name: Building plugin
      run: |
        make
        zip system_cover-qemu_5_2.zip libsystem_cover.so
    - name: Uploading plugin
      uses: actions/upload-artifact@v2
      with:
        name: Plugin for QEMU 5.2
        path: '*.zip'

  qemu_6_0:
    name: Plugin build for QEMU 6.0
    runs-on: ubuntu-latest
    steps:
    - name: Cloning plugin repo
      uses: actions/checkout@v2
    - name: Cloning qemu repo
      uses: actions/checkout@v2
      with:
          repository: qemu/qemu
          ref: v6.0.0
          path: ./qemu
    - name: Building plugin
      run: |
        make
        zip system_cover-qemu_6_0.zip libsystem_cover.so
    - name: Uploading plugin
      uses: actions/upload-artifact@v2
      with:
        name: Plugin for QEMU 6.0
        path: '*.zip'

  release:
    name: Plugin release
    needs: [qemu_4_2, qemu_5_0, qemu_5_1, qemu_5_2, qemu_6_0]
    runs-on: ubuntu-latest
    steps:
      - name: Downloading plugins
        uses: actions/download-artifact@v2
      - name: Releasing
        uses: softprops/action-gh-release@v1
        with:
          files: '**/*.zip'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
